// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIe0GRnvL10yC4pEjmYTwSzNMCzdra1D4',
    appId: '1:400150350771:web:68a020f085660fee7999c6',
    messagingSenderId: '400150350771',
    projectId: 'e-commerce-app-fbb02',
    authDomain: 'e-commerce-app-fbb02.firebaseapp.com',
    storageBucket: 'e-commerce-app-fbb02.firebasestorage.app',
    measurementId: 'G-1VBCSD0RZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgpvkjojwmPfilUqSUh4aBL0KEM3eYJqA',
    appId: '1:400150350771:android:1f019028487bf4fe7999c6',
    messagingSenderId: '400150350771',
    projectId: 'e-commerce-app-fbb02',
    storageBucket: 'e-commerce-app-fbb02.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCM64oX9FT_GzCYBJeeYqHHXrY2ix1M1gc',
    appId: '1:400150350771:ios:9823f38758687c787999c6',
    messagingSenderId: '400150350771',
    projectId: 'e-commerce-app-fbb02',
    storageBucket: 'e-commerce-app-fbb02.firebasestorage.app',
    androidClientId: '400150350771-d8kjpknsgg4pgpb5itjugr40etblmn45.apps.googleusercontent.com',
    iosClientId: '400150350771-olhu8ecl6elodeb82v0bpccjkf2cfepi.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCM64oX9FT_GzCYBJeeYqHHXrY2ix1M1gc',
    appId: '1:400150350771:ios:9823f38758687c787999c6',
    messagingSenderId: '400150350771',
    projectId: 'e-commerce-app-fbb02',
    storageBucket: 'e-commerce-app-fbb02.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIe0GRnvL10yC4pEjmYTwSzNMCzdra1D4',
    appId: '1:400150350771:web:99c127a03bb5f5577999c6',
    messagingSenderId: '400150350771',
    projectId: 'e-commerce-app-fbb02',
    authDomain: 'e-commerce-app-fbb02.firebaseapp.com',
    storageBucket: 'e-commerce-app-fbb02.firebasestorage.app',
    measurementId: 'G-MV5WV04GT0',
  );
}
